defmodule Bumblebee.Multimodal.Blip2 do
  alias Bumblebee.Shared

  options =
    [
      vision_spec: [
        default: nil,
        doc:
          "the specification of the vision model. See `Bumblebee.Vision.BlipVision` for details"
      ],
      qformer_spec: [
        default: nil,
        doc:
          "the specification of the Q-Former model. See `Bumblebee.Text.Blip2Qformer` for details"
      ],
      text_spec: [
        default: nil,
        doc: "the specification of the text (language) model"
      ]
    ]

  @moduledoc """
  The BLIP-2 model for vision-language tasks.

  BLIP-2 extends BLIP with a Q-Former bridge between frozen image encoders
  and frozen large language models. The Q-Former's output is projected to the
  language model's embedding space and prepended to the text input embeddings
  as visual soft prompts.

  ## Architectures

    * `:for_conditional_generation` - BLIP-2 model with a language
      modeling head for conditional text generation

  ## Inputs

    * `"pixel_values"` - `{batch_size, image_size, image_size, num_channels}`

      Featurized image pixel values.

    * `"decoder_input_ids"` - `{batch_size, target_sequence_length}`

      Indices of decoder input sequence tokens in the vocabulary. If not
      present and `"input_ids"` is, it will be generated by shifting
      each token in `"input_ids"` to the right once.

    * `"decoder_attention_mask"` - `{batch_size, target_sequence_length}`

      Mask indicating which decoder tokens to attend to. This is used
      to ignore padding tokens, which are added when processing a batch
      of sequences with different length.

    * `"decoder_position_ids"` - `{batch_size, target_sequence_length}`

      Indices of positions of each decoder input sequence tokens in
      the position embeddings.

    * `"encoder_hidden_state"` - `{batch_size, sequence_length, hidden_size}`

      Last hidden state output from the vision-language bridge. If
      specified, the model will skip the image encoding and Q-Former
      process and use this value directly as the projected visual
      embeddings prepended to the text input.

    * `"cache"`

      A container with cached layer results used to speed up sequential
      decoding (autoregression). With cache, certain hidden states are
      taken from the cache, rather than recomputed on every decoding
      pass. The cache should be treated as opaque and initialized with
      `Bumblebee.Text.Generation.init_cache/4`.

  ## Global layer options

  #{Shared.global_layer_options_doc([:output_hidden_states, :output_attentions])}

  ## Configuration

  #{Shared.options_doc(options)}

  ## References

    * [BLIP-2: Bootstrapping Language-Image Pre-training with Frozen Image Encoders and Large Language Models](https://arxiv.org/abs/2301.12597)

  """

  defstruct [architecture: :for_conditional_generation] ++ Shared.option_defaults(options)

  @behaviour Bumblebee.ModelSpec
  @behaviour Bumblebee.Configurable
  @behaviour Bumblebee.Text.Generation

  alias Bumblebee.Layers

  @impl true
  def architectures(), do: [:for_conditional_generation]

  @impl true
  def config(spec, opts) do
    Shared.put_config_attrs(spec, opts)
  end

  @impl true
  def input_template(%{vision_spec: vision_spec}) do
    vision_shape = {1, vision_spec.image_size, vision_spec.image_size, vision_spec.num_channels}

    %{
      "pixel_values" => Nx.template(vision_shape, :f32),
      "decoder_input_ids" => Nx.template({1, 1}, :u32)
    }
  end

  @impl true
  def model(%__MODULE__{architecture: :for_conditional_generation} = spec) do
    %{vision_spec: vision_spec, qformer_spec: qformer_spec, text_spec: text_spec} = spec

    vision_shape =
      {nil, vision_spec.image_size, vision_spec.image_size, vision_spec.num_channels}

    text_shape = {nil, nil}
    text_hidden_shape = {nil, nil, text_spec.hidden_size}

    inputs =
      Bumblebee.Utils.Model.inputs_to_map([
        Axon.input("pixel_values", shape: vision_shape),
        Axon.input("decoder_input_ids", optional: true, shape: text_shape),
        Axon.input("decoder_attention_mask", optional: true, shape: text_shape),
        Axon.input("decoder_position_ids", optional: true, shape: text_shape),
        Axon.input("encoder_hidden_state", optional: true, shape: text_hidden_shape),
        Axon.input("cache", optional: true)
      ])

    # Step 1: Build vision model
    vision_model =
      vision_spec
      |> Bumblebee.build_model()
      |> Bumblebee.Utils.Axon.prefix_names("vision_model.")
      |> Bumblebee.Utils.Axon.plug_inputs(%{
        "pixel_values" => inputs["pixel_values"]
      })

    vision_hidden_state = Axon.nx(vision_model, & &1.hidden_state)

    # Step 2: Feed vision output to Q-Former as cross-attention input
    qformer_model =
      qformer_spec
      |> Bumblebee.build_model()
      |> Bumblebee.Utils.Axon.prefix_names("qformer.")
      |> Bumblebee.Utils.Axon.plug_inputs(%{
        "encoder_hidden_state" => vision_hidden_state
      })

    qformer_output = Axon.nx(qformer_model, & &1.hidden_state)

    # Step 3: Project Q-Former output to text decoder hidden dimension
    language_projection =
      Axon.dense(qformer_output, text_spec.hidden_size,
        name: "language_projection"
      )

    # Use pre-computed encoder_hidden_state if available, otherwise use projected Q-Former output
    projected_hidden_state =
      Layers.if_present inputs["encoder_hidden_state"] do
        inputs["encoder_hidden_state"]
      else
        language_projection
      end

    # Step 4: Feed projected Q-Former output as input_embeddings to the language model.
    # The projected visual embeddings act as soft prompts prepended to the text input.
    text_decoder =
      text_spec
      |> Bumblebee.build_model()
      |> Bumblebee.Utils.Axon.prefix_names("language_model.")
      |> Bumblebee.Utils.Axon.plug_inputs(%{
        "input_ids" => inputs["decoder_input_ids"],
        "attention_mask" => inputs["decoder_attention_mask"],
        "position_ids" => inputs["decoder_position_ids"],
        "input_embeddings" => projected_hidden_state,
        "cache" => inputs["cache"]
      })

    Layers.output(%{
      logits: Axon.nx(text_decoder, & &1.logits),
      decoder_hidden_states: Axon.nx(text_decoder, & &1.hidden_states),
      decoder_attentions: Axon.nx(text_decoder, & &1.attentions),
      encoder_hidden_state: projected_hidden_state,
      cache: Axon.nx(text_decoder, & &1.cache)
    })
  end

  @impl true
  def init_cache(
        %{text_spec: text_spec},
        batch_size,
        max_length,
        inputs
      ) do
    inputs =
      %{
        "input_ids" => inputs["decoder_input_ids"],
        "attention_mask" => inputs["decoder_attention_mask"],
        "position_ids" => inputs["decoder_position_ids"]
      }
      |> Map.reject(&match?({_, nil}, &1))

    text_spec.__struct__.init_cache(text_spec, batch_size, max_length, inputs)
  end

  @impl true
  def traverse_cache(_spec, cache, fun) do
    Layers.Decoder.traverse_cache(cache, fun)
  end

  defimpl Bumblebee.HuggingFace.Transformers.Config do
    def load(spec, data) do
      import Shared.Converters

      {vision_data, data} = Map.pop(data, "vision_config", %{})
      {qformer_data, data} = Map.pop(data, "qformer_config", %{})
      {text_data, data} = Map.pop(data, "text_config", %{})

      vision_spec =
        Bumblebee.Vision.BlipVision
        |> Bumblebee.configure()
        |> Bumblebee.HuggingFace.Transformers.Config.load(vision_data)

      qformer_spec =
        Bumblebee.Text.Blip2Qformer
        |> Bumblebee.configure()
        |> Bumblebee.HuggingFace.Transformers.Config.load(qformer_data)

      # Determine text model type from the config
      text_model_type = text_data["model_type"]

      text_module =
        case text_model_type do
          "opt" -> Bumblebee.Text.Opt
          _ -> Bumblebee.Text.Opt
        end

      text_spec =
        text_module
        |> Bumblebee.configure(architecture: :for_causal_language_modeling)
        |> Bumblebee.HuggingFace.Transformers.Config.load(text_data)

      opts =
        convert!(data, []) ++ Shared.common_options_from_transformers(data, spec)

      @for.config(
        spec,
        opts ++ [vision_spec: vision_spec, qformer_spec: qformer_spec, text_spec: text_spec]
      )
    end
  end

  defimpl Bumblebee.HuggingFace.Transformers.Model do
    alias Bumblebee.HuggingFace.Transformers

    def params_mapping(spec) do
      vision_mapping =
        spec.vision_spec
        |> Transformers.Model.params_mapping()
        |> Transformers.Utils.prefix_params_mapping("vision_model", nil)

      qformer_mapping =
        spec.qformer_spec
        |> Transformers.Model.params_mapping()
        |> Transformers.Utils.prefix_params_mapping("qformer", nil)

      text_mapping =
        spec.text_spec
        |> Transformers.Model.params_mapping()
        |> Transformers.Utils.prefix_params_mapping("language_model", nil)

      %{
        "language_projection" => "language_projection"
      }
      |> Map.merge(vision_mapping)
      |> Map.merge(qformer_mapping)
      |> Map.merge(text_mapping)
    end
  end
end
