defmodule Bumblebee.Multimodal.Florence2 do
  alias Bumblebee.Shared

  options =
    [
      vision_spec: [
        default: nil,
        doc:
          "the specification of the vision model. See `Bumblebee.Vision.Davit` for details"
      ],
      text_spec: [
        default: nil,
        doc:
          "the specification of the text (encoder-decoder) model. See `Bumblebee.Text.Bart` for details"
      ],
      projection_size: [
        default: nil,
        doc:
          "the dimensionality of the vision-to-text projection layer. Defaults to the text model hidden size"
      ]
    ]

  @moduledoc """
  Florence-2 model for multimodal conditional generation.

  Florence-2 composes a DaViT vision backbone with a BART-like
  encoder-decoder text model via a projection layer.

  ## Architectures

    * `:for_conditional_generation` - Florence-2 model with a language
      modeling head

  ## Inputs

    * `"pixel_values"` - `{batch_size, image_size, image_size, num_channels}`

      Featurized image pixel values.

    * `"input_ids"` - `{batch_size, sequence_length}`

      Indices of input sequence tokens in the vocabulary.

    * `"attention_mask"` - `{batch_size, sequence_length}`

      Mask indicating which tokens to attend to. This is used to ignore
      padding tokens, which are added when processing a batch of sequences
      with different length.

    * `"decoder_input_ids"` - `{batch_size, target_sequence_length}`

      Indices of decoder input sequence tokens in the vocabulary. If not
      present and `"input_ids"` is, it will be generated by shifting
      each token in `"input_ids"` to the right once.

    * `"decoder_attention_mask"` - `{batch_size, target_sequence_length}`

      Mask indicating which decoder tokens to attend to. This is used
      to ignore padding tokens, which are added when processing a batch
      of sequences with different length.

    * `"encoder_hidden_state"` - `{batch_size, sequence_length, hidden_size}`

      Last hidden state output from the encoder. This hidden state is
      used in cross-attention blocks in the decoder. If specified, the
      model will skip the vision and text encoding process and use this
      value directly for cross-attentions in the decoder.

    * `"cache"`

      A container with cached layer results used to speed up sequential
      decoding (autoregression). With cache, certain hidden states are
      taken from the cache, rather than recomputed on every decoding
      pass. The cache should be treated as opaque and initialized with
      `Bumblebee.Text.Generation.init_cache/4`.

  ## Global layer options

  #{Shared.global_layer_options_doc([:output_hidden_states, :output_attentions])}

  ## Configuration

  #{Shared.options_doc(options)}

  ## References

    * [Florence-2: Advancing a Unified Representation for a Variety of Vision Tasks](https://arxiv.org/abs/2311.06242)

  """

  defstruct [architecture: :for_conditional_generation] ++ Shared.option_defaults(options)

  @behaviour Bumblebee.ModelSpec
  @behaviour Bumblebee.Configurable
  @behaviour Bumblebee.Text.Generation

  alias Bumblebee.Layers

  @impl true
  def architectures(), do: [:for_conditional_generation]

  @impl true
  def config(spec, opts) do
    Shared.put_config_attrs(spec, opts)
  end

  @impl true
  def input_template(%{vision_spec: vision_spec}) do
    vision_shape = {1, vision_spec.image_size, vision_spec.image_size, vision_spec.num_channels}

    %{
      "pixel_values" => Nx.template(vision_shape, :f32),
      "input_ids" => Nx.template({1, 1}, :u32),
      "decoder_input_ids" => Nx.template({1, 1}, :u32)
    }
  end

  @impl true
  def model(%__MODULE__{architecture: :for_conditional_generation} = spec) do
    %{vision_spec: vision_spec, text_spec: text_spec} = spec

    text_hidden_size = text_spec.hidden_size

    vision_shape = {nil, vision_spec.image_size, vision_spec.image_size, vision_spec.num_channels}
    text_shape = {nil, nil}
    encoder_hidden_shape = {nil, nil, text_hidden_size}

    inputs =
      Bumblebee.Utils.Model.inputs_to_map([
        Axon.input("pixel_values", shape: vision_shape),
        Axon.input("input_ids", optional: true, shape: text_shape),
        Axon.input("attention_mask", optional: true, shape: text_shape),
        Axon.input("decoder_input_ids", optional: true, shape: text_shape),
        Axon.input("decoder_attention_mask", optional: true, shape: text_shape),
        Axon.input("decoder_position_ids", optional: true, shape: text_shape),
        Axon.input("encoder_hidden_state", optional: true, shape: encoder_hidden_shape),
        Axon.input("cache", optional: true)
      ])

    # Build the DaViT vision model
    vision_model =
      vision_spec
      |> Bumblebee.build_model()
      |> Bumblebee.Utils.Axon.prefix_names("vision_tower.")
      |> Bumblebee.Utils.Axon.plug_inputs(%{
        "pixel_values" => inputs["pixel_values"]
      })

    vision_model_outputs =
      Layers.if_present inputs["encoder_hidden_state"] do
        %{
          hidden_state: inputs["encoder_hidden_state"],
          hidden_states: Layers.none(),
          attentions: Layers.none()
        }
      else
        %{
          hidden_state: Axon.nx(vision_model, & &1.hidden_state),
          hidden_states: Axon.nx(vision_model, & &1.hidden_states),
          attentions: Axon.nx(vision_model, & &1.attentions)
        }
      end

    # Project vision features to text hidden dimension
    projection_size = spec.projection_size || text_hidden_size

    projected_vision_state =
      vision_model_outputs.hidden_state
      |> Axon.dense(projection_size,
        name: "image_projection.linear_1"
      )
      |> Axon.activation(:gelu)
      |> Axon.dense(projection_size,
        name: "image_projection.linear_2"
      )

    # Build the BART-like encoder-decoder text model
    # The text model receives the projected vision features as encoder_hidden_state
    text_model =
      text_spec
      |> Bumblebee.build_model()
      |> Bumblebee.Utils.Axon.prefix_names("language_model.")
      |> Bumblebee.Utils.Axon.plug_inputs(%{
        "input_ids" => inputs["input_ids"],
        "attention_mask" => inputs["attention_mask"],
        "decoder_input_ids" => inputs["decoder_input_ids"],
        "decoder_attention_mask" => inputs["decoder_attention_mask"],
        "decoder_position_ids" => inputs["decoder_position_ids"],
        "encoder_hidden_state" => projected_vision_state,
        "cache" => inputs["cache"]
      })

    Layers.output(%{
      logits: Axon.nx(text_model, & &1.logits),
      decoder_hidden_states: Axon.nx(text_model, & &1.decoder_hidden_states),
      decoder_attentions: Axon.nx(text_model, & &1.decoder_attentions),
      cross_attentions: Axon.nx(text_model, & &1.cross_attentions),
      encoder_hidden_state: projected_vision_state,
      encoder_hidden_states: vision_model_outputs.hidden_states,
      encoder_attentions: vision_model_outputs.attentions,
      cache: Axon.nx(text_model, & &1.cache)
    })
  end

  @impl true
  def init_cache(
        %{vision_spec: vision_spec, text_spec: text_spec},
        batch_size,
        max_length,
        inputs
      ) do
    # The encoder sequence length comes from the vision model's spatial tokens
    num_patches = div(vision_spec.image_size, vision_spec.patch_size)
    num_stages = length(vision_spec.depths)
    # After hierarchical downsampling, the final spatial resolution
    final_resolution = div(num_patches, 2 ** (num_stages - 1))
    encoder_sequence_length = final_resolution * final_resolution

    encoder_shape = {batch_size, encoder_sequence_length, text_spec.hidden_size}

    inputs =
      %{
        "input_ids" => inputs["input_ids"],
        "attention_mask" => inputs["attention_mask"],
        "decoder_input_ids" => inputs["decoder_input_ids"],
        "decoder_attention_mask" => inputs["decoder_attention_mask"],
        "decoder_position_ids" => inputs["decoder_position_ids"],
        "encoder_hidden_state" => Nx.template(encoder_shape, :f32)
      }
      |> Map.reject(&match?({_, nil}, &1))

    text_spec.__struct__.init_cache(text_spec, batch_size, max_length, inputs)
  end

  @impl true
  def traverse_cache(_spec, cache, fun) do
    Layers.Decoder.traverse_cache(cache, fun)
  end

  defimpl Bumblebee.HuggingFace.Transformers.Config do
    def load(spec, data) do
      import Shared.Converters

      {vision_data, data} = Map.pop(data, "vision_config", %{})
      {text_data, data} = Map.pop(data, "text_config", %{})

      vision_spec =
        Bumblebee.Vision.Davit
        |> Bumblebee.configure()
        |> Bumblebee.HuggingFace.Transformers.Config.load(vision_data)

      text_spec =
        Bumblebee.Text.Bart
        |> Bumblebee.configure(architecture: :for_conditional_generation)
        |> Bumblebee.HuggingFace.Transformers.Config.load(text_data)

      opts =
        convert!(data,
          projection_size: {"projection_dim", number()}
        ) ++ Shared.common_options_from_transformers(data, spec)

      @for.config(spec, opts ++ [text_spec: text_spec, vision_spec: vision_spec])
    end
  end

  defimpl Bumblebee.HuggingFace.Transformers.Model do
    alias Bumblebee.HuggingFace.Transformers

    def params_mapping(spec) do
      text_mapping =
        spec.text_spec
        |> Transformers.Model.params_mapping()
        |> Transformers.Utils.prefix_params_mapping("language_model", nil)

      vision_mapping =
        spec.vision_spec
        |> Transformers.Model.params_mapping()
        |> Transformers.Utils.prefix_params_mapping("vision_tower", nil)

      %{
        "image_projection.linear_1" => "image_projection.linear_1",
        "image_projection.linear_2" => "image_projection.linear_2"
      }
      |> Map.merge(text_mapping)
      |> Map.merge(vision_mapping)
    end
  end
end
