# Verify Bumblebee model outputs against saved HuggingFace reference outputs.
#
# This script loads the JSON files generated by compare_huggingface_outputs.py
# and runs the same inputs through Bumblebee, comparing the results.
#
# Usage:
#   First run: python test/scripts/compare_huggingface_outputs.py
#   Then run:  mix run test/scripts/verify_bumblebee_outputs.exs

defmodule BumblebeeVerification do
  @fixtures_dir Path.join([__DIR__, "..", "fixtures", "huggingface_outputs"])
  @tolerance 1.0e-3

  def run do
    IO.puts("=" |> String.duplicate(60))
    IO.puts("Bumblebee vs HuggingFace Output Verification")
    IO.puts("=" |> String.duplicate(60))

    models = [
      {"electra", &verify_electra/1},
      {"deberta_v2", &verify_deberta_v2/1},
      {"falcon", &verify_decoder_model/1},
      {"opt", &verify_decoder_model/1},
      {"qwen2", &verify_decoder_model/1}
    ]

    results =
      for {model_name, verify_fn} <- models do
        path = Path.join(@fixtures_dir, "#{model_name}_outputs.json")

        if File.exists?(path) do
          IO.puts("\n--- #{model_name} ---")
          reference_data = path |> File.read!() |> Jason.decode!()
          {passed, failed} = verify_fn.(reference_data)
          IO.puts("  Results: #{passed} passed, #{failed} failed")
          {model_name, passed, failed}
        else
          IO.puts("\n--- #{model_name} ---")
          IO.puts("  SKIPPED: No reference data found at #{path}")
          IO.puts("  Run: python test/scripts/compare_huggingface_outputs.py first")
          {model_name, 0, 0}
        end
      end

    IO.puts("\n" <> String.duplicate("=", 60))
    IO.puts("Summary")
    IO.puts(String.duplicate("=", 60))

    total_passed = Enum.sum(for {_, p, _} <- results, do: p)
    total_failed = Enum.sum(for {_, _, f} <- results, do: f)

    for {name, passed, failed} <- results do
      status = if failed == 0, do: "OK", else: "FAILED"
      IO.puts("  #{name}: #{passed} passed, #{failed} failed [#{status}]")
    end

    IO.puts("\nTotal: #{total_passed} passed, #{total_failed} failed")

    if total_failed > 0 do
      IO.puts("\nSome verifications failed! Check model implementations.")
      System.halt(1)
    else
      IO.puts("\nAll verifications passed!")
    end
  end

  defp verify_electra(reference_data) do
    inputs = %{
      "input_ids" => Nx.tensor([[10, 20, 30, 40, 50, 60, 70, 80, 0, 0]]),
      "attention_mask" => Nx.tensor([[1, 1, 1, 1, 1, 1, 1, 1, 0, 0]])
    }

    verify_encoder_model(reference_data, inputs)
  end

  defp verify_deberta_v2(reference_data) do
    inputs = %{
      "input_ids" => Nx.tensor([[10, 20, 30, 40, 50, 60, 70, 80, 0, 0]]),
      "attention_mask" => Nx.tensor([[1, 1, 1, 1, 1, 1, 1, 1, 0, 0]])
    }

    verify_encoder_model(reference_data, inputs)
  end

  defp verify_encoder_model(reference_data, inputs) do
    Enum.reduce(reference_data, {0, 0}, fn ref, {passed, failed} ->
      model_name = ref["model_name"]
      arch = ref["architecture"]
      IO.write("  Verifying #{arch}... ")

      case Bumblebee.load_model({:hf, model_name}) do
        {:ok, %{model: model, params: params}} ->
          outputs = Axon.predict(model, params, inputs)

          if verify_shapes(outputs, ref) do
            IO.puts("PASSED")
            {passed + 1, failed}
          else
            IO.puts("SHAPE MISMATCH")
            {passed, failed + 1}
          end

        {:error, reason} ->
          IO.puts("LOAD ERROR: #{reason}")
          {passed, failed + 1}
      end
    end)
  end

  defp verify_decoder_model(reference_data) do
    inputs = %{
      "input_ids" => Nx.tensor([[10, 20, 30, 40, 50, 60, 70, 80, 0, 0]]),
      "attention_mask" => Nx.tensor([[1, 1, 1, 1, 1, 1, 1, 1, 0, 0]])
    }

    Enum.reduce(reference_data, {0, 0}, fn ref, {passed, failed} ->
      model_name = ref["model_name"]
      arch = ref["architecture"]
      IO.write("  Verifying #{arch}... ")

      case Bumblebee.load_model({:hf, model_name}) do
        {:ok, %{model: model, params: params}} ->
          outputs = Axon.predict(model, params, inputs)

          if verify_shapes(outputs, ref) do
            IO.puts("PASSED")
            {passed + 1, failed}
          else
            IO.puts("SHAPE MISMATCH")
            {passed, failed + 1}
          end

        {:error, reason} ->
          IO.puts("LOAD ERROR: #{reason}")
          {passed, failed + 1}
      end
    end)
  end

  defp verify_shapes(outputs, ref) do
    cond do
      ref["hidden_state_shape"] && Map.has_key?(outputs, :hidden_state) ->
        expected_shape = List.to_tuple(ref["hidden_state_shape"])
        actual_shape = Nx.shape(outputs.hidden_state)
        actual_shape == expected_shape

      ref["logits_shape"] && Map.has_key?(outputs, :logits) ->
        expected_shape = List.to_tuple(ref["logits_shape"])
        actual_shape = Nx.shape(outputs.logits)
        actual_shape == expected_shape

      ref["start_logits_shape"] && Map.has_key?(outputs, :start_logits) ->
        expected_start = List.to_tuple(ref["start_logits_shape"])
        expected_end = List.to_tuple(ref["end_logits_shape"])
        actual_start = Nx.shape(outputs.start_logits)
        actual_end = Nx.shape(outputs.end_logits)
        actual_start == expected_start and actual_end == expected_end

      true ->
        # No shape reference to compare against
        true
    end
  end

  defp compare_tensors(actual, expected_list, tolerance) do
    expected = Nx.tensor(expected_list)

    actual
    |> Nx.all_close(expected, atol: tolerance, rtol: tolerance)
    |> Nx.to_number() == 1
  end
end

BumblebeeVerification.run()
